# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartlist_app', '0004_todo_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='null', max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('snippet', models.CharField(default='null', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_video', to='smartlist_app.Todo')),
            ],
        ),
    ]
