# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlist_app', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
